// ─── USERS ───────────────────────────────────────────────────────────────────

export const users = [
  {
    id: "u1",
    name: "Arjun Sharma",
    college: "RV College of Engineering",
    year: "2nd",
    age: 20,
    bio: "RVCE mech guy. Always down for something new.",
    vibes: ["🎉 Party animal", "🏕️ Adventurous"],
    ratings: [],
  },
  {
    id: "u2",
    name: "Priya Mehta",
    college: "BMS College of Engineering",
    year: "3rd",
    age: 21,
    bio: "BMS CS. Love cafes and exploring Bangalore.",
    vibes: ["🤙 Chill", "🍕 Foodie"],
    ratings: [],
  },
  {
    id: "u3",
    name: "Karan Patel",
    college: "MSRIT",
    year: "1st",
    age: 19,
    bio: "MSRIT fresher. Sports and adventures.",
    vibes: ["💬 Outgoing", "🏃 Active"],
    ratings: [],
  },
]

// ─── PLANS ───────────────────────────────────────────────────────────────────

export const plans = [
  {
    id: "PLAN-A1B2C3",
    title: "Brewery Crawl 🍺",
    type: "Party",
    location: "Indiranagar",
    date: "2026-06-12",
    time: "7:00 PM",
    description: "Hitting the best spots in Indiranagar. Good vibes only.",
    isPublic: true,
    maxMembers: 8,
    creatorId: "u1",
    memberIds: ["u1", "u2"],
    requestIds: [],
    tags: ["🎉 Party animal", "💬 Outgoing"],
    itinerary: [
      { id: "i1", time: "7:00 PM", activity: "Meet at Toit", note: "First round here" },
      { id: "i2", time: "9:00 PM", activity: "Move to Arbor", note: "Happy hour" },
    ],
    itineraryPermission: "all",
    chat: [],
  },
  {
    id: "PLAN-D4E5F6",
    title: "Coorg Weekend 🏕️",
    type: "Trip",
    location: "Coorg",
    date: "2026-06-18",
    time: "5:00 AM",
    description: "Weekend trip to Coorg. Camping and coffee estates.",
    isPublic: true,
    maxMembers: 6,
    creatorId: "u2",
    memberIds: ["u2"],
    requestIds: ["u3"],
    tags: ["🏕️ Adventurous", "🌿 Nature lover"],
    itinerary: [],
    itineraryPermission: "creator",
    chat: [],
  },
  {
    id: "PLAN-G7H8I9",
    title: "Sunday Football ⚽",
    type: "Sports",
    location: "Koramangala",
    date: "2026-06-13",
    time: "6:00 AM",
    description: "Morning football near Forum Mall. All levels welcome.",
    isPublic: true,
    maxMembers: 14,
    creatorId: "u3",
    memberIds: ["u3", "u1"],
    requestIds: [],
    tags: ["🏃 Active", "💬 Outgoing"],
    itinerary: [],
    itineraryPermission: "all",
    chat: [],
  },
]